service: ohell-sockets-v1

provider:
  name: aws
  runtime: nodejs12.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

functions:
  connectHandler:
    handler: handlers.onconnect
    events:
      - websocket:
          route: $disconnect
  disconnectHandler:
    handler: handlers.ondisconnect
    events:
        - websocket:
            route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket: $default #simple event definition without extra route property
