# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env: # Or as an environment variable
          AWS_ACCESS_KEY_ID_NONPROD_ADMIN: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_ADMIN }}
          AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN }}
        run: |
          yarn -v
          cd server
          yarn
          echo attempting deploy using $AWS_ACCESS_KEY_ID_NONPROD_ADMIN
          yarn deploy
