# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, OH009-deploy-ui-with-aws-s3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: deploy API
        env:
          AWS_ACCESS_KEY_ID_NONPROD_ADMIN: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_ADMIN }}
          AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN }}
        run: |
          yarn -v
          cd server
          yarn
          echo attempting deploy using $AWS_ACCESS_KEY_ID_NONPROD_ADMIN
          yarn deploy
      - name: deploy UI
        env:
          AWS_ACCESS_KEY_ID_NONPROD_ADMIN: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_ADMIN }}
          AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN }}
          DEST: ohell-ui-dev
        run: |
          cd client
          yarn
          yarn build
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_NONPROD_ADMIN
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_NONPROD_ADMIN
          aws s3 rm s3://$DEST --recursive
          aws s3 sync $PWD/build s3://$DEST --content-encoding gzip
